---
downloads: ~/.ansible-downloads/

configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: git@github.com:ddepaoli3/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/workspace/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitconfig
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc
  - .zshrc
  - .bash_aliases

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - bash-completion
  - git
  - gpg
  - mcrypt
  - nmap
  - ssh-copy-id
  - readline
  - openssl
  - pv
  - wget
  - p7zip
  - pass
  - packer
  - node
  - openssl
  - tig

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/php
  - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  # - fing # Download link keeps getting changed, d'oh!
  - google-chrome
  - limechat
  - macvim
  - slack
  - sublime-text
  - vagrant
  - virtualbox
  - iterm2
  - jumpcut
  - keepassx
  - insync
  - filezilla
  - go2shell
  - google-drive
  - keybase
  - openoffice
  - pycharm-ce
  - qtpass
  - screenhero
  - skype
  - spotify
  - telegram
  - vlc
  - wireshark
  - coconutbattery
  - tunnelblick
  - fritzing
  - wakeonlan
  - torbrowser

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""
